/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
}

dependencies {
    api(project(":btx-framework-boot"))
    api("com.baomidou:mybatis-plus-boot-starter")
    api(project(":btx-framework-core"))
    api("org.flywaydb:flyway-core")
}

tasks {
    jar {
        enabled = true
        archiveClassifier.set("")
    }

}
