/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
}

dependencies {
    api("cn.hutool:hutool-crypto")
}

description = "btx-framework-core"


tasks {
    jar {
        enabled = true
        archiveClassifier.set("")
    }
}
