/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    id("org.springframework.boot")
}

dependencies {
    api(project(":btx-framework-boot"))
    api("org.springframework.boot:spring-boot-starter-web")
    api("com.alibaba:fastjson")
    api(project(":btx-framework-core"))
    api("com.squareup.okhttp3:okhttp")
}

description = "btx-framework-boot-web"

tasks {
    jar {
        enabled = true
        archiveClassifier.set("")
    }

}
