/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
}

dependencies {
    api(project(":btx-framework-boot-cache"))
    api(project(":btx-framework-boot-security-shiro"))
}

group = "top.cheesetree.btx.framework.security"
description = "btx-framework-boot-security-shiro-redis"

tasks {
    jar {
        enabled = true
        archiveClassifier.set("")
    }

}
