/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    id("org.springframework.boot")
}

dependencies {
    api(project(":btx-framework-boot-cache"))
    api("org.springframework.session:spring-session-data-redis")
}

description = "btx-framework-boot-session"

tasks {
    jar {
        enabled = true
        archiveClassifier.set("")
    }

}
