/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    id("org.springframework.boot")
}

dependencies {
    api(project(":btx-framework-boot"))
    api(project(":btx-framework-core"))
    api("org.springframework.boot:spring-boot-starter-data-redis")
    api("org.apache.commons:commons-pool2")
    api("com.alibaba:fastjson")
    api("org.redisson:redisson-spring-boot-starter")
}

tasks {
    jar {
        enabled = true
        archiveClassifier.set("")
    }

    bootJar {
        enabled = false
    }
}
