/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    id("org.springframework.boot")
}

dependencies {
    api("org.springframework.boot:spring-boot-starter")
    api("org.projectlombok:lombok")
}

tasks {
    jar {
        enabled = true
        archiveClassifier.set("")
    }

    bootJar {
        enabled = false
    }
}
